### ISSUE TITLE
Error true position and negative values

### ISSUE THREAD

**Issue by legau** [legau/kanon-api#26]
On `/ephemerides/moon/true_pos/?day=17&month=11&year=30` :
```python
Traceback (most recent call last):
  File "./kanon_api/routes/ephemerides.py", line 48, in get_true_pos
    pos = moon_true_pos(date)
  File "./kanon_api/core/ephemerides/true_position.py", line 28, in moon_true_pos
    mean_sun_pos = Sun.mean_motion(days)
  File "./kanon_api/core/ephemerides/utils.py", line 40, in func
    return mod(parameter * days + radix) * degree
  File "/home/vscode/.cache/pypoetry/virtualenvs/kanon-api-9sQvTUES-py3.9/lib/python3.9/site-packages/kanon/units/radices.py", line 1155, in __mul__
    return BasedQuantity(self, unit=other)
  File "/home/vscode/.cache/pypoetry/virtualenvs/kanon-api-9sQvTUES-py3.9/lib/python3.9/site-packages/kanon/units/radices.py", line 1342, in __new__
    self = super().__new__(cls, value, unit=unit, dtype=object, **kwargs)
  File "/home/vscode/.cache/pypoetry/virtualenvs/kanon-api-9sQvTUES-py3.9/lib/python3.9/site-packages/astropy/units/quantity.py", line 346, in __new__
    elif (isiterable(value) and len(value) > 0 and
TypeError: object of type 'Sexagesimal' has no len()
```
Also negative Mars values are returned.

**Comment by legau** [comment]
Venus over 360 at `1723668`
